### PR TITLE
Update src/com/palmergames/bukkit/towny/command/TownCommand.java

### PR DESCRIPTION
**Pull request by poliuy**
Can I get a towny file with this change? I would LOVE to have it say nation instead of town so it would involve people more into the rp elements.

### CODE REVIEW

**Comment by Zren** [comment]
How does making everything in /town ? use the nation prefix make it more rp?

**Comment by poliuy** [comment]
Well on my server I want to use towny like such:

Player joins server

Player wants to join a nation

Player types /nation join ?

Player then becomes a part of that nation

The problem I am having with towny (and btw it is an amazing plugin so thank you for putting the hard work and effort into it) is that I don't know how to remove the town layer? I feel as if that is one layer too much like I just want to have nations like the plugin has. I would be fine with just towns, but you can't go to war with other towns =/.

Also on another note, when you walk into an area it says like "town name (settlement) pvp home" how do I get rid of that so it would just show the towns name?

Anyway thank you so much.

**Comment by Zren** [comment]
Ah, I know what you mean, there are a fair amount of things I'd change if I started over from scratch. An no I won't be compiling that, sorry. As you will want it for every update and I'm not doing that... I'll bug ElgarL to add those to the language file though.
Town levels. just remove all the prefix/suffixs.

**Comment by Zren** [comment]
Factions is a good plugin if your looking for just one layer. I haven't checked it out in a long time though.

**Comment by poliuy** [comment]
Not a problem, I knew it was a long shot, thank you however for your advice and again thank you for the awesome plugin =).

**Pull request closed without merging**
